name: Sabertooth-io
author: Sabertooth-io
baseurl: /herring-cove
description: A Javascript library for building web applications with Bluetooth.
github: http://www.github.com/sabertooth-io
twitter:
facebook:
linkedin:
email:
location:
disqus:

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
